name: Create Issue with Current Time in Markdown

on:
  schedule:
    - cron: '16 * * * *' # Runs every hour at 44 minutes

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run Python Script to Get Dates
        id: get-dates
        run: |
          python3 script/date.py > dates.md

      - name: Read Markdown Content
        id: read-dates
        run: |
          echo "content=$(cat dates.md | base64)" >> $GITHUB_ENV

      - name: Create GitHub Issue
        uses: actions/github-script@v6
        with:
          script: |
            const content = Buffer.from(process.env.content, 'base64').toString('utf-8');
            const { data: issue } = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Current Time in Markdown Format`,
              body: content
            });
            console.log(`Created issue: ${issue.html_url}`);